#@data/values
---
tanzunet:
  username: user@example.com
  password:
ceip_policy_disclosed: true # Installation fails if this is set to 'false'
ingress:
  domain: example.com # In case you want to use a subdomain(e.g. tap.aws.example.com) of your configured hosted zone(e.g. aws.example.com), you have to change the "--domain-filter=" argument value for the external-dns Deployment in the ingress-config/external-dns.yaml to the hosted zone domain(e.g. aws.example.com) instead of the variable value (which is the subdomain)!
  contour_tls_namespace: tanzu-system-ingress
container_registry:
  hostname: harbor.example.com
  project: tap
  project_workload: tap-wkld
  username: admin
  password: 
gitrepo:
  host: github.com
  token: <github_token>
catalog:
  location: https://github.com/<CATALOG-INFO-REPO>/git-catalog/blob/main/catalog-info.yaml
