---
### used by service accounts associated with deployment in the Tanzu Application Platform
###
### this scc should be only used by the following service accounts
###   - system:serviceaccount:tanzu-system-ingress:contour
###   - system:serviceaccount:flux-system:default
###
###

kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
  name: application-platform-general-scc

###
### values needed for the security context for tanzu application platform components
### see role bindings below for service accounts allowed to use
###
runAsUser:
  type: MustRunAsRange
  uidRangeMin: 65532
  uidRangeMax: 65534

###
### required values in a security context controller
###
allowHostDirVolumePlugin: false
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegedContainer: false
readOnlyRootFilesystem: false
seLinuxContext:
  type: MustRunAs

---
###
### cluster role for binding serviceaccount to constraint
###
### reference for binding serviceaccount to constraint
### https://docs.openshift.com/container-platform/4.6/authentication/managing-security-context-constraints.html#role-based-access-to-ssc_configuring-internal-oauth
###
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: application-platform-general-cluster-role
rules:
  - apiGroups:
      - security.openshift.io
    resourceNames:
      - application-platform-general-scc
    resources:
      - securitycontextconstraints
    verbs:
      - use
---
###
### role binding for binding serviceaccount to constraint
###
apiVersion: rbac.authorization.k8s.io/v1
# This cluster role binding grants "contour" service account in the tanzu-system-ingress namespace membership to ClusterRole application-platform-envoy-cluster-role
# This cluster role binding grants "default" service account in the flux-system namespace membership to ClusterRole application-platform-envoy-cluster-role
kind: ClusterRoleBinding
metadata:
  name: application-platform-general-cluster-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: application-platform-general-cluster-role
subjects:
  - kind: ServiceAccount
    namespace: tanzu-system-ingress
    name: contour
  - kind: ServiceAccount
    namespace: flux-system
    name: default
